### ISSUE TITLE
Use the React State Hook

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/plotgallery#9]
I'm learning React :) Should we use the [State Hook](https://reactjs.org/docs/hooks-state.html)? That seems to make state handling a bit easier and apparently is the new way of doing things?

**Comment by TonyLianLong** [comment]
In this project, we currently use classes to create react components. How State Hook works is that it's possible that we use only functions, not classes, to create components with states. The react document says:

> If you write a function component and realize you need to add some state to it, previously you had to convert it to a class. Now you can use a Hook inside the existing function component. We’re going to do that right now!

In the old times, we cannot add State to functions. Now, with the help of State Hook, we can. However, since we are already writing classes, there is not much need to use State Hook. I personally would choose to write a function as a react component when the component is simple enough. I would write a class otherwise. For me it seems that using classes is a little easier for others to understand a complex react component than using a function with State Hooks.
